version: '3'

services:
  li-php:
    build: '.docker'
    container_name: php
    hostname: li-php
    volumes:
      - .:/var/www
    ports:
      - 9000:9000
    networks:
      - li-php

networks:
  li-php:
    driver: bridge